repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest (unit tests)
        entry: conda run -n projects-student-template pytest tests/ -v
        language: system
        pass_filenames: false
        always_run: true
